plugin: aws_ec2
regions:
  - eu-west-2
filters:
  instance-state-name: running
compose:
  ansible_host: public_ip_address
keyed_groups:
  - key: tags.Name
    prefix: tag_Name_
hostnames:
  - dns-name
  - private-ip-address


