---
plugin: aws_ec2
regions:
  - eu-west-2
filters:
  tag:Name: app-server
  instance-state-name: running
keyed_groups:
  - key: tags
    prefix: tag
  - key: instance_type
    prefix: instance_type
destination_variable: public_ip_address

