plugin: aws_ec2
regions:
  - eu-west-2

filters:
  instance-state-name: running
  tag:app-server:
    - "true"

compose:
  ansible_host: public_ip_address

keyed_groups:
  - key: tags.app-server
    prefix: tag_app-server_

hostnames:
  - dns-name
  - private-ip-address
