plugin: aws_ec2
regions:
  - eu-west-2
filters:
  instance-state-name: running
  tag:Name:
    - "app-server"
compose:
  ansible_host: public_ip_address
destination_variable: public_ip_address
keyed_groups:
  - key: tags.Name
    prefix: tag_Name
