- name: Setup Docker and run Nginx container
  hosts: tag_Name_app_server
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Install Docker using amazon-linux-extras (Amazon Linux 2)
      shell: |
        amazon-linux-extras install -y docker
      args:
        creates: /usr/bin/docker
      when: ansible_distribution == "Amazon"

    - name: Install Docker on RedHat (not Amazon Linux)
      yum:
        name: docker
        state: present
      when: ansible_os_family == "RedHat" and ansible_distribution != "Amazon"

    - name: Update package cache on Debian/Ubuntu
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Docker on Debian/Ubuntu
      apt:
        name: docker.io
        state: present
      when: ansible_os_family == "Debian"

    - name: Install python3-pip on Amazon Linux 2
      shell: |
        yum install -y python3-pip
      args:
        creates: /usr/bin/pip3
      when: ansible_distribution == "Amazon"

    - name: Install python3-pip on RedHat (not Amazon Linux)
      yum:
        name: python3-pip
        state: present
      when: ansible_os_family == "RedHat" and ansible_distribution != "Amazon"

    - name: Install python3-pip on Debian/Ubuntu
      apt:
        name: python3-pip
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Docker Python SDK using pip3
      pip:
        name: docker
        executable: pip3

    - name: Start and enable Docker service on RedHat/Amazon Linux
      systemd:
        name: docker
        state: started
        enabled: yes
      when: ansible_os_family == "RedHat"

    - name: Start and enable Docker service on Debian/Ubuntu
      service:
        name: docker
        state: started
        enabled: yes
      when: ansible_os_family == "Debian"

    - name: Pull latest nginx image
      docker_image:
        name: nginx
        source: pull

    - name: Run nginx container
      docker_container:
        name: nginx
        image: nginx:latest
        state: started
        restart_policy: always
        ports:
          - "80:80"
