- name: Install Docker
  hosts: tag_Name_app-server
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

- name: Install Docker Compose
  hosts: tag_Name_app-server
  become: yes
  tasks:
    - name: Install Docker Compose
      pip:
        name: docker-compose
        state: present

- name: Run Nginx container
  hosts: tag_Name_app-server
  become: yes
  tasks:
    - name: Pull Nginx image
      docker_image:
        name: nginx
        source: pull

    - name: Run Nginx container
      docker_container:
        name: nginx
        image: nginx
        state: started
        restart_policy: always
        published_ports:
          - "80:80"
