---
- name: Setup Docker and run Nginx container
  hosts: tag_Name_app_server
  become: yes

  tasks:
    - name: Update package cache on Debian/Ubuntu
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Update package cache on RedHat/Amazon Linux
      yum:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Install Docker on Debian/Ubuntu
      apt:
        name: docker.io
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Docker on RedHat/Amazon Linux
      yum:
        name: docker
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install python3-pip on Debian/Ubuntu
      apt:
        name: python3-pip
        state: present
      when: ansible_os_family == "Debian"

    - name: Install python3-pip on RedHat/Amazon Linux
      yum:
        name: python3-pip
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install Docker Python SDK (docker module)
      pip:
        name: docker
        executable: pip3

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull latest nginx image
      docker_image:
        name: nginx
        source: pull

    - name: Run Nginx container
      docker_container:
        name: nginx
        image: nginx
        state: started
        ports:
          - "80:80"
