- name: Setup Docker and run Nginx container
  hosts: tag_Name_app_server
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Install Docker Compose
      pip:
        name: docker-compose
        state: present

    - name: Install Docker Python module for Ansible
      pip:
        name: docker
        state: present

    - name: Ensure Docker service is started and enabled
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Pull Nginx image
      docker_image:
        name: nginx
        source: pull

    - name: Run Nginx container
      docker_container:
        name: nginx
        image: nginx
        state: started
        restart_policy: always
        published_ports:
          - "80:80"